# coding=utf-8
import enum


class TabId(enum.Enum):
    BATCH_GENERATE = 0
    BATCH2LINE_ART = 1
    GENERATE_LINE_ART_CLUSTERING = 2
    TRY_COLOR_GAME = 3
    GAN_EXTRACT_LINE = 4
    GENERATE_LINE_ART_SVG = 5
    IMAGE2SVG = 6
    BATCH_GENERATE_V2 = 7
    BATCH_MJ_GENERATE = 8
    BATCH_FLUX_GENERATE = 9
    LINE_ART2SVG = 10
